spring.application.name=pulsedesk

spring.datasource.url=jdbc:h2:mem:pulsedeskdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

huggingface.api.token=${HF_TOKEN}
huggingface.api.url=https://router.huggingface.co/v1/chat/completions
huggingface.api.model=openai/gpt-oss-120b